name: Turist Guide
favicon: null
layout_spectrum: 0.14742
typography_spectrum: 0.18986134650185704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01aef0'
    - '#ba131a'
    - '#626262'
    - '#a8a8a8'
  brandStrength: 0.2315777544863522
  lightness: 0.7169918708968908
  saturation: 0.4518261149059981
  rhythmicContrast: 0.43623724416829646
purpose: []
